### ISSUE TITLE
colon in folderpath

### ISSUE THREAD

**Issue by bjuergens** [SmartDataInnovationLab/dirhash#4]
dirhash crashes, when the folderpath contains ":"

critical because hashes contain ":"

workaround: replace ":" with "_"

**Comment by bjuergens** [comment]
error-message: 

```
[ugfam@bi-01-login dev]$ spark-submit --master yarn --deploy-mode client --jars $HOME/dev/dirhash/target/sparkhacks-0.0.1-SNAPSHOT.jar $HOME/dev/dirhash/dirhash.py $HOME/dev/test\:data 2>/dev/null
spark.yarn.driver.memoryOverhead is set but does not apply in client mode.
Traceback (most recent call last):
  File "/smartdata/ugfam/dev/dirhash/dirhash.py", line 620, in <module>
    _main(sys.argv)
  File "/smartdata/ugfam/dev/dirhash/dirhash.py", line 609, in _main
    h = hash_directory(args.dir, args.hash_algo, args.blocksize)
  File "/smartdata/ugfam/dev/dirhash/dirhash.py", line 455, in hash_directory
    raw_hash = hash_directory_raw(dir, algo, _parse_blocksize(blocksize), sparkcontext)
  File "/smartdata/ugfam/dev/dirhash/dirhash.py", line 327, in hash_directory_raw
    return hash_directory_raw(dir, algo, blocksize, sc)
  File "/smartdata/ugfam/dev/dirhash/dirhash.py", line 339, in hash_directory_raw
    stderr=subprocess.PIPE
  File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['hadoop', 'fs', '-ls', '-R', '/smartdata/ugfam/dev/test:data']' returned non-zero exit status 255
```

And when you run the interal command, you get: 

```
[ugfam@bi-01-login dev]$ hadoop fs -ls -R /smartdata/ugfam/dev/test\:data
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
18/04/09 16:36:05 INFO gpfs.GeneralParallelFileSystem: load gpfslib
-ls: java.net.URISyntaxException: Relative path in absolute URI: test:data
Usage: hadoop fs [generic options] -ls [-d] [-h] [-R] [<path> ...]
```

**Comment by bjuergens** [comment]
According to [this blog](https://labs.totango.com/reading-a-file-with-colon-from-s3-in-spark-e8f467c290ea) the colon has a special meaning and is not allowed paths in hadoop file-system. 

the best solution is probably to turn the ":" in dirhash into "-" (or something similiar)

**Comment by bjuergens** [comment]
List of illegal characters in hadoop paths: 

>Path elements MUST NOT be in {"", ".", "..", "/"}.
>Path elements MUST NOT contain the characters {'/', ':'}.

[source](https://hadoop.apache.org/docs/r2.5.2/hadoop-project-dist/hadoop-common/filesystem/model.html)

**Comment by bjuergens** [comment]
Till agrees --> we'll use "-" instead of ":"
